cli: remove the 'Caused by' section in the error message (#424)
### What

https://hasurahq.atlassian.net/browse/V3DX-1053

Before:

```
$ CONNECTION_URI="postgresql://re" cargo run --bin ndc-postgres-cli -- --context='/tmp/baba' update
Error: error communicating with database: failed to lookup address information: Name or service not known

Caused by:
    failed to lookup address information: Name or service not known
```

After:

```
$ CONNECTION_URI="postgresql://re" cargo run --bin ndc-postgres-cli -- --context='/tmp/baba' update
ERROR: error communicating with database: failed to lookup address information: Name or service not known
```

### How

Instead of having a `main() -> anyhow::Result<()>`, we explicitly handle
printing the error.

https://docs.rs/anyhow/1.0.69/anyhow/struct.Error.html#display-representations